### ISSUE TITLE
Easylist blocks images

### ISSUE THREAD

**Issue by AndreaMdq** [easylist/easylist#159]
Easylist should not block some images in http://www.hoyts.com.ar

**Comment by monzta** [comment]
Please provide more details.

**Comment by AndreaMdq** [comment]
In the site you will see that an image is blocked by Easylist: 

![image](https://cloud.githubusercontent.com/assets/22546652/21570719/87aaf2f4-cea7-11e6-8d21-ab7779f428d6.png)


If I turn the filter off, the image is displayed correctly:

![image](https://cloud.githubusercontent.com/assets/22546652/21570824/5b579c42-cea8-11e6-82da-77856466689e.png)

I hope you can help me. 
Thanks.

**Comment by monzta** [comment]
Fixed https://github.com/easylist/easylist/commit/e9209a6ff41dd652c139909dece70fb480dacdb5

**Comment by AndreaMdq** [comment]
Sorry, but is not fixed yet: 

![image](https://cloud.githubusercontent.com/assets/22546652/21766847/86e71c58-d64f-11e6-959c-6b5840d0c354.png)

Thanks.
