### ISSUE TITLE
techtimes.com social list blocks video and easylist issue

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#170]
http://www.techtimes.com/articles/169154/20160709/9-messaging-apps-with-end-to-end-encryption-facebook-messenger-whatsapp-imessage-and-more.htm

Social list blocks the video. The video's audio still plays, but there's no picture.
@ryanbr

**Comment by terrorist96** [comment]
http://www.techtimes.com/articles/151802/20160420/viber-adds-end-to-end-encryption-following-footsteps-of-whatsapp-and-apple.htm

Easylist blocks the video on the right, but the audio still plays.. so you can't stop the audio from playing.

**Comment by monzta** [comment]
Fixed https://github.com/easylist/easylist/commit/83f9a8d77287e4f4e6068fcbd1cc3d9e71e2746d

**Comment by terrorist96** [comment]
@monzta The second link is still broken. The page blocks the video ad, but the audio from the ad still plays in the background, and since the video itself is blocked, it's impossible to mute the audio of the ad unless you mute your speakers.
