### ISSUE TITLE
agrobomduarte.com

### ISSUE THREAD

**Issue by virtualwebgit** [easylist/easylist#18576]
#### Your settings:

- OS/version: Windows 11
- Browser/version: Google Chrome x64 121.0.6167.185
- Ad block extension/version: uBlock Origin 1.55.0

**Comment by libalpm64** [comment]
Hello please add this to your filter list in your UBLOCK origin filters:
`||www.agrobomduarte.com/comum/cookies.php`
This should solve your issue!

**Comment by partingscientist** [comment]
@Yuki2718 Should be fixed with https://github.com/easylist/easylist/commit/f982d684a8ba4c462cc0d0c6c513633bfed8e7a7.

**Comment by virtualwebgit** [comment]
Still showing

<img width="1513" height="785" alt="Image" src="https://github.com/user-attachments/assets/dd9472cf-e29c-47e1-be4d-f41965d7770c" />

**Comment by partingscientist** [comment]
@virtualwebgit Have you enabled "Easylist Cookie"? It's hidden on my end, unless you can show how it looks like while doing inspect element.

**Comment by virtualwebgit** [comment]
> [@virtualwebgit](https://github.com/virtualwebgit) Have you enabled "Easylist Cookie"? It's hidden on my end, unless you can show how it looks like while doing inspect element.

Yes, it is

<img width="1595" height="725" alt="Image" src="https://github.com/user-attachments/assets/ce8dc07c-d42d-4d3c-b7ee-10842ae390c9" />
