### ISSUE TITLE
(NSFW) recaptcha on imagefap.com false positive

### ISSUE THREAD

**Issue by thaliel** [easylist/easylist#235]
the recaptcha that is 2 images of random terms is currently being blocked by easylist

**Comment by SMed79** [comment]
An example pages where we can reproduce the issue?

**Comment by thaliel** [comment]
I suppose any page that uses this recaptcha version. I found it when trying to send a message on imagefap, but you would only be able to reproduce that if you are a member

**Comment by thaliel** [comment]
This problem still persists, and I cannot find the filter responsible for the recaptcha module being blocked on imagefap

**Comment by SMed79** [comment]
Submit an adblock plus [issue report](https://adblockplus.org/en/getting_started#false-positives) and post the link here or at [easylist forum](https://forums.lanik.us/viewtopic.php?p=113609#p113609).

**Comment by thaliel** [comment]
http://www.imagefap.com/message.php, though I suppose this will only work if have an IF account

**Comment by SMed79** [comment]
try these filters
```
imagefap.com#@#[id][style*="width:"]
imagefap.com#@#div > div > div > [class]:first-child
imagefap.com#@#table[cellpadding] td div > [id]:last-child
```

**Comment by thaliel** [comment]
wonderful, thank you

**Comment by Khrin** [comment]
This has been fixed in EasyList, https://github.com/easylist/easylist/commit/8d4b486e2d3b9d24be8b3e46d92098a15c549f1e
You can remove the custom filters.

**Comment by thaliel** [comment]
unfrotunately, the recaptcha is being hidden AGAIN

**Comment by Khrin** [comment]
Fixed: https://github.com/easylist/easylist/commit/5a60bfc217f192e5cdc7954aed7baa15a3634fd7

**Comment by thaliel** [comment]
No, this is not fixed, the recaptcha is currently not showing

**Comment by Khrin** [comment]
Update the EasyList subscription in a few minutes.

**Comment by thaliel** [comment]
and it is gone again, this is getting utterly frustrating

**Comment by Khrin** [comment]
Fixed: https://github.com/easylist/easylist/commits/master

**Comment by thaliel** [comment]
let's see how long it lasts this time

**Comment by thaliel** [comment]
new day,  new way of IF to annoy us. 
http://www.imagefap.com/gallery.php ,amongst oher IF sections, will no longer diplay their central modules
