### ISSUE TITLE
Breaks the buttons on dfiles.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [easylist/easylist#308]
https://github.com/easylist/easylist/commit/4f0de7e3441bf8dee681e3b6769400be1036d2ca

This commit breaks the buttons on dfiles.ru:
http://dfiles.ru/files/bidfzbmso

**Comment by Khrin** [comment]
Should be working now. https://github.com/easylist/easylist/commit/2572b1f1741e25322aeed4ab2c4a6e77b5433842

**Comment by dimisa-RUAdList** [comment]
The problem is not solved! 
The button is not clickable > http://i.imgur.com/y4dg3ws.jpg

**Comment by Khrin** [comment]
Works perfectly for me.

**Comment by dimisa-RUAdList** [comment]
https://vid.me/T46y
https://reports.adblockplus.org/ee40adba-55b7-47d5-8478-204dcc90c2de#tab=requests

**Comment by Khrin** [comment]
Thank you, don't know why but I see their files coming only from `static.depositfiles.com`, instead of `static.dfiles.ru`.

**Comment by dimisa-RUAdList** [comment]
Ok,
Thanks!
