### ISSUE TITLE
Wrongfully Blocking /v1/events again

### ISSUE THREAD

**Issue by sontek** [easylist/easylist#4067]
# List the website(s) you're having issues:
https://eventray.com API is having issues, specifically:

https://api.eventray.com/v1/events/?event.include=permissions&org_id=ae6594f6-64a2-4d67-a81e-3ff2702163ec&limit=100&offset=0

### What happens?

EasyList is currently blocking us even those we are a conference management / event management company.  We have nothing to do with tracking people.

I originally reported the issue here:

https://github.com/easylist/easylist/issues/4039

These tickets are also the exact same issue:

https://github.com/easylist/easylist/issues/4056
https://github.com/easylist/easylist/issues/4060

### List Subscriptions you're using:

<img width="823" alt="Screenshot 2019-09-25 09 06 20" src="https://user-images.githubusercontent.com/151924/65613868-e227c100-df73-11e9-8fb3-23375e9e5827.png">

### Your settings

- OS/version: OSX
- Browser/version: Chrome v77
- Adblock Extension/version: Version 3.55.1

### Other details:

<img width="688" alt="Screenshot 2019-09-25 09 06 40" src="https://user-images.githubusercontent.com/151924/65613909-f4096400-df73-11e9-9afe-87be5ebc2e76.png">

I think it might be better to start a blacklist of sites that you're trying to block with these 2 checks.  So far from the issues list I've noticed it has broken:

- calendar events
- parties and events
- error events

I think its just too generic the way you're attempting to do it now.   This is the second time our customers have had the site broken by the rule after it had been fixed previously

**Comment by sontek** [comment]
Seems like this is the commit that caught us in the crossfire this time:

https://github.com/easylist/easylist/commit/8e8d71a886159b502258a3a6ebcc3b8c8d613e31

**Comment by ohcannotangel** [comment]
Same issue for us.
It breaks our API like:

```
/v2/events;param1=value1;param2=value2?foo=bar
```

We provide a calendar service which has a large number of users.
This rule is way too generic, so we hope this two rules will be removed.

**Comment by iMarv** [comment]
Same issue for us. The filter is targeted on one fraudulent website but is breaking a heavy amount of others.
By running a popular list like this you have a certain degree of responsibility not breaking half of the web with your filters.
Please consider removing the entry as it is not only hurting companies running websites but also your list as it is turning the user experience of using these filters into a nuisance.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7f665ff00d4bd031f9cf0610b21a2a187ba0cc8f

should resolve it.

**Comment by iMarv** [comment]
Did not for us.
Still having issues with `/v1/events`, alternatively with query params.
Just remove the entries and create a blacklist like @sontek suggested, rather than shooting into the blind.

**Comment by max06** [comment]
@ryanbr Can you please revert 8e8d71a and 7f665ff as soon as possible, before this change leads to irreparable reputational damage?

I'm not sure if there's some kind of automatic testing for new/changed rules, if they're overblocking valid content. If not, you should definitely add something like that...

**Comment by kalmant** [comment]
We are having the same issue with our service. It also has nothing to do with tracking, it is one of our core features and blocking it makes our site unusable. Please fix this ASAP!

Thank you!

**Comment by ryanbr** [comment]
To all people commenting on this thread.

There has been no reproducible examples being handed over. So how can we test this? Adding a "me too" basically doesn't help anyone.

**Comment by max06** [comment]
@ryanbr Well, there's at least one example on the issue description itself about how such an XHR call looks like. Even without, why would you add a filter you can't test and where you have no idea if it might cause trouble?

If you're targeting one fraudulent website, why not just blocking that one instead of blocking a path that's used by a lot of regular applications and APIs? 

(Serious questions, not trying to hit you, personally I like the work you're doing!)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/7f665ff00d4bd031f9cf0610b21a2a187ba0cc8f

**From the example:**

This commit should fix the issues, because the filter will stop processing after the last `|`, So it won't block `/v2/events;param1=value1;param2=value2?foo=bar`

**Comment by MrBlaise** [comment]
Hey!

I am not sure it is smart to put such strict rules in a widely used list such as this. There are a bunch of endpoints listed without specifying the domain. It is almost impossible to make it bulletproof this way and it could potentially (just like with the /v1/events) cause companies lose some customers.

Once these lists are updated it is very hard to regain trust, we can't just tell the customers hey please update your adblocker. We respect the user's privacy and thus won't and can't just send them spam emails every time something like this happens.

Thank you for your efforts of creating this list and I hope you consider figuring out a way to decrease the number of "domainless" rules.

**Comment by ermescs** [comment]
I have an example that was broken before the 7f665ff00d4bd031f9cf0610b21a2a187ba0cc8f commit:
https://www.gazzetta.it/calcio/serie-a/partita/torino-milan/2021102/notizie?refresh_ce

The above commit fixes this particular case. However, I'm afraid these rules are still way too generic.

It's quite easy for me to imagine the existence of some kind of REST API with a resource endpoint structured in this way:
`GET|POST /api/<api version>/events`

As @sontek mentioned, this may easily happen for, e.g., calendar apps, log management services, etc.

I understand the need of real world examples, and I'm quite confident they will emerge. However, as others have mentioned, I also think that a safer approach would be to somehow restrict the websites on which this rule applies.

I do not know the original reason that brought to the existence of these rules. But the issue could probably be mitigated by adding a `third-party` flag or by specifying on which domains the rules must be applied.

Anyway, thanks for the great effort in creating and maintaining this list!

**Comment by ryanbr** [comment]
In short, this filter won't be removed.  The example of gazzetta.it (above) was fixed in the last commit. Please update the lists, then refresh the page. These filters are blocking event logging, which is a privacy issue. And because of this, it has to stay because privacy is king. 

If there is a site that has actual usable issues, that we can reproduce by anyone/public/us we can review with a whitelist if need be. But to let event tracker/logging stay unblocked would be a disservice to anyone relying on a privacy-oriented list (like Easyprivacy).

/# end of thread. And update your lists.

**Comment by iMarv** [comment]
Out of pure interest, if we are going to start tracking our users through `/accounts` or even better `/easylist`, ist that going to be added to the filters aswell?

**Comment by MrBlaise** [comment]
I disagree with this argument. This is just plain old blacklist, if the people who want to steal user information just rename their endpoints they can easily circumvent this list.

If one site starts using `/v1/users` endpoint to collect information about users thus violating their privacy, would you blacklist `/v1/users`? Of course not that would be careless, because thousands of APIs use this endpoint for user management. This logic applies to every "domainless" endpoint. 

Let me go further. Let's just put `*` in the list so that everyone is safe.

**Comment by Khrin** [comment]
Two upvotes in one minute? I'm impressed.

**Comment by max06** [comment]
@ryanbr Who are you that you define which urls can be used for what purpose?

**Comment by ermescs** [comment]
@ryanbr Honestly, I do not understand the hard tone you used in your last comment.

If you read my comment carefully, I clearly stated that the gazzetta.it example is indeed fixed by the commit you referenced. So it is quite obvious that I had already updated my filter lists...

Obviously, I'm not saying that these rules should be completely removed. Because, as you said, privacy is king, and personally I do care a lot about privacy. But I still think that these rules are too broad and potentially very harmful for legitimate services. Come on, the example api endpoint I gave speaks for itself...

I, as other people, still think that you should somehow restrict these specific rules, and that a whitelisting approach may still be "risky".

Hopefully someone will give you real examples that will make you consider changing these rules.

**Comment by nikolak** [comment]
Events does not mean tracking. Events is such a generic term which, while it may be abused in some cases, it still remains very generic and used for a lot of other purposes. The right approach would be to blacklist those who abuse /v1/events as opposed to require everyone else to be added to a whitelist for using a generic term.

All the comments here keep saying "events" all you hear @ryanbr is "[privacy invading] event _logging_".

**Comment by ryanbr** [comment]
Note, "Blacklist those who abuse <insert string>" Given we don't run these sites, who knows? @nikolak  And going by publicwww search even logging seems pretty prevalent.

The fact the event logging business **is a privacy issue** is still a completely valid argument. And anyone in the business of event-logging will always jump and down if we add any generic rules targeting them, the end user has no opt-out by default.

**Comment by MrBlaise** [comment]
We are still havin issue. GET requests are working on /v1/events?someparam... endpoint, but when we try to POST to /v1/events it will be blocked.

This endpoint is for creating a learning event for people who want to learn about IT security, not a privacy issue.

**Comment by MrBlaise** [comment]
@ryanbr We are not an event logging business. We teach it security and people can schedule events for their teams with hands-on challenges. I hardly think this is an event-logging company....

**Comment by c-stoeckl** [comment]
> Note, "Blacklist those who abuse " Given we don't run these sites, who knows? @nikolak And going by publicwww search even logging seems pretty prevalent.
> 
> The fact the event logging business **is a privacy issue** is still a completely valid argument. And anyone in the business of event-logging will always jump and down if we add any generic rules targeting them, the end user has no opt-out by default.

Ryan, like @nikolak said you keep hearing "logging" but its not about logging as everyone is trying really hard to explain to you.

**Comment by ryanbr** [comment]
Not this thread is being watched by them (as the event logging urls have been changing). Not assuming everyone is in the event logging/tracking business. but most them will be aware of this thread.

I've removed the filters for the time being, https://github.com/easylist/easylist/commit/0b2ea95733151178c0815da53a2456fa0ba38e1b   It'll be reviewed again later.

**Comment by max06** [comment]
Another example: I'm using `/v1/events` for a websocket connection, to transmit backend events to a frontend... Nothing related to tracking.

**Comment by wachri** [comment]
@max06 same use case here

**Comment by MrBlaise** [comment]
@Khrin How childish of you. We raise a valid argument, you attack me than you write your comment in a locked issue where you know I would not be able to answer. 

![image](https://user-images.githubusercontent.com/3867275/65761229-b0069280-e11e-11e9-9de7-b97d53439bd7.png)

I am questioning whether this list should be used blindly in adblockers if you don't listen to common sense and valid arguments.
