### ISSUE TITLE
Wrong entry in EasyPrivacy list

### ISSUE THREAD

**Issue by joopbraak** [easylist/easylist#4099]
Because of that, Dutch foodticket websites are not working properly.
For instance:
https://www.sushisu.nl/
Fill in the postcode (for instance 1092AA) and nothing happens.
If I disable EasyPrivacy list in adblock plus it works.
I tried in Firefox and Chromium, same result. I think it's one of the
cloudfront.net entries.
Must have been added recently because it still worked not so long ago.

Can you please solve this? Thank you very much!

P.S. Foodticket makes websites for restaurants for ordering food online.

**Comment by Khrin** [comment]
Should be fixed for this domain, do you know if there are more affected?

**Comment by joopbraak** [comment]
What do you mean by this domain? https://www.sushisu.nl ?

I tried another foodticket website, it had the same problem.
https://pizzaadamsplash.foodticket.nl/

Updated EasyPrivacy list, it still doesn't work, or is the commit not immedialely updated in the list?

Thanks!

**Comment by joopbraak** [comment]
Ah. I see now, you added an exception for that specific website.

I think it's a general cloudfront.net rule that prevents ALL foodticket websites from working, so I think adding an exception for all these websites separately is not the real solution (more like a work around).

Thanks

**Comment by Khrin** [comment]
Yes, it was. Now I've modified accordingly, so isn't anymore domain specific. https://github.com/easylist/easylist/commit/299f9f8472b07b8a2e89e507ffcdb69dca2180c4 You'll have to wait a 15/20 minutes or so to have changes rolled out and try to update your adblocking software. I hope you won't miss your dinner...

**Comment by joopbraak** [comment]
Thank you very much, fast service! I was courageous and temporarely disabled the EasyPrivacy list, to be able to order the sushi.

Hope their service is as fast as yours! :-)
