### ISSUE TITLE
policeone.com unblocked ad

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#416]
`https://www.policeone.com/suspect-pursuit/articles/83338-Law-enforcement-pursuits-Managing-the-risks-Part-1/`

Sponsored by Pursuit Response

**Comment by zero77** [comment]
This PR should fix it #417

**Comment by terrorist96** [comment]
@Khrin @ryanbr I still see the Sponsored by Pursuit Response. Please reopen.

**Comment by Khrin** [comment]
https://github.com/easylist/easylist/commit/7b0b81433307fadc6124c362902900202185ef2c
