### ISSUE TITLE
Grammarist.com ads in Chrome

### ISSUE THREAD

**Issue by terrorist96** [easylist/easylist#5]
https://forums.lanik.us/viewtopic.php?f=62&t=30469&p=94147#p94147

**Comment by monzta** [comment]
Should fix it: https://github.com/easylist/easylist/commit/f1825286e78c9aa23e4324b4d9df1edf42bd489f

**Comment by terrorist96** [comment]
@monzta it doesn't fix it. I still see ads in Chrome when I block 3rd party cookies. Please see my comments in the thread. Merging one of intense's filters fixes the issue..

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/00a840b5a1c2c2cbb9ef60abbccf83a6bf822f12

**Comment by terrorist96** [comment]
@monzta I still see the ads on Chrome with 3rd party cookies blocked lol.

**Comment by terrorist96** [comment]
@monzta

**Comment by terrorist96** [comment]
@monzta you missed this one

**Comment by monzta** [comment]
https://github.com/easylist/easylist/commit/040d254c926006becb3a4b1126f8b41de0cf6e34
