### ISSUE TITLE
promo.* rule too broad

### ISSUE THREAD

**Issue by Kryniol** [easylist/easylist#5717]
### List the website(s) you're having issues:

All the Promo.com subscribers using our app and embedding videos with iframe on their websites. Example:
`https://promo-prod.myshopify.com/products/nnew-sofa`

### What happens?

I'm a backend dev in a team which builds and maintains a Promo.com Photos To Video Maker app, allowing users to create promotional videos using chosen photos. Recently we've introduced an iframe generator as a way to embed videos created by our users in their websites. After they create a video in the app they can copy an iframe HTML tag and manually paste it in their product pages. The iframe is being blocked by AdBlock due to the [rule](https://github.com/easylist/easylist/blob/2a91edb554d7ab208ca0ac2aa5195080456c46b2/easylist/easylist_general_block.txt#L7222):

`://promo.$third-party`

which for some reason blocks everything from any domain having the word "promo" in its name. Promo.com, though, is a perfectly legal startup providing tools for creating promotional videos and is not involved in any kind of unwanted advertising.

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: Ubuntu 20.04
- Browser/version: Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- Adblock Extension/version: Adblock 4.15.0

### Other details:

It's already a 3rd time we're experiencing issues with releasing new features in our apps because of the EasyList rule.
The rule has been added in [this commit](https://github.com/easylist/easylist/commit/d070b277931be2f642fea92badd622cb0b022e4d) and it was not related to any of the promo.com sites.

Related issue: https://github.com/easylist/easylist/issues/4703

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/38641039a47b524e99569580f5860b6534646de5

fixed

**Comment by Kryniol** [comment]
@ryanbr this doesn't fix the issue, as I mentioned the iframe snipped can be embedded in **any** website, I gave just an example but the issue is not related to .myshopify.com domain.

**Comment by Kryniol** [comment]
@ryanbr please revert the commit, removing existing rules breaks the embedded code for our existing users, they don't necessarily use .myshopify.com domain.

**Comment by ryanbr** [comment]
does this work?

https://github.com/easylist/easylist/commit/564480e1b67ef2c1208017ae0d7cfbb3ee3dc557

**Comment by ryanbr** [comment]
tested against https://promo-prod.myshopify.com/products/nnew-sofa?variant=32187273805899

**Comment by Kryniol** [comment]
@ryanbr whitelisting a domain where the iframe code would be embedded won't help in our case, our users can paste the snippet in any website (I gave you just an example of a website, please disregard its domain, it can be anything). Can you exclude promo.com from the promo.* rule as it seems to be way too broad? I also described the problem in detail (see the issue description), when the promo.* rule was added it had nothing in common with our domain.

**Comment by llacb47** [comment]
Read the commit again, he did that.
