### ISSUE TITLE
opentip.kaspersky.com

### ISSUE THREAD

**Issue by SeriousHoax** [easylist/easylist#5823]
### List the website(s) you're having issues:
`https://opentip.kaspersky.com/`

### What happens?

Cookie notice
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/88667146-cbf21080-d102-11ea-8494-fa0bef99f73e.png)

</details><br/>
### List Subscriptions you're using:
Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List 

### Your settings

- OS/version: Windows 10 2004
- Browser/version: Firefox 78.0.2
- Adblock Extension/version: uBlock Origin 1.28.4

### Other details:

There was already a commit related to this site which worked at that time but looks like they have changed something recently. 
Previous commit: 
https://github.com/easylist/easylist/pull/5541

**Comment by SeriousHoax** [comment]
@Yuki2718 Can you check this one out too? Another cookie notice
`https://my.kaspersky.com/`

**Comment by Yuki2718** [comment]
> @Yuki2718 Can you check this one out too? Another cookie notice
> `https://my.kaspersky.com/`

`##wp-cookie-notification-banner` will be enough. I believe @ryanbr will soon fix it too.

**Comment by SeriousHoax** [comment]
Fixed

**Comment by Yuki2718** [comment]
Well, apparently I still get the cookie notice with up-to-date Fanboy Annoyances.

**Comment by SeriousHoax** [comment]
> Well, apparently I still get the cookie notice with up-to-date Fanboy Annoyances.

Do you mean for `https://my.kaspersky.com/`? 
I actually made another pull request for that: https://github.com/easylist/easylist/pull/5892

**Comment by Yuki2718** [comment]
`###` and `##` are semantically different.
