### ISSUE TITLE
www9.0123movies.com

### ISSUE THREAD

**Issue by TheFilterGuy** [easylist/easylist#6030]
### List the website(s) you're having issues:

```https://www9.0123movies.com/```

### What happens?

Popup not blocked

### List Subscriptions you're using:

EasyList

### Your settings

- OS/version: macOS
- Browser/version: Chrome
- Adblock Extension/version: AdBlock Plus 

### Other details:

![Captura de Pantalla 2020-09-07 a la(s) 20 56 03](https://user-images.githubusercontent.com/70922433/92421003-d44f5980-f14c-11ea-9605-db2daddc0d48.png)

**Comment by ryanbr** [comment]
Fixed

**Comment by TheFilterGuy** [comment]
Not fixed. Took these screenshots just now

![Captura de Pantalla 2020-09-08 a la(s) 17 33 53](https://user-images.githubusercontent.com/70922433/92525219-d1f70900-f1f9-11ea-88c8-9f662e548c18.png)
![Captura de Pantalla 2020-09-08 a la(s) 17 33 55](https://user-images.githubusercontent.com/70922433/92525221-d3c0cc80-f1f9-11ea-8f54-c8967ed74aae.png)
![Captura de Pantalla 2020-09-08 a la(s) 17 33 52](https://user-images.githubusercontent.com/70922433/92525225-d4596300-f1f9-11ea-8dea-606b72106f29.png)
