### ISSUE TITLE
mp3download.to popups

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylist#9912]
### List the website(s) you're having issues:

`https://mp3download.to/26-downloader`

### What happens?

Popups with crap requets

<img width="478" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/144268632-e49e3aa8-157a-4486-8a36-dbb7ff251b99.PNG">

### List Subscriptions you're using:

uBlock Origin default with EasyList, EasyPrivacy and EasyList germany

### Your settings

- OS/version: win 10
- Browser/version: Firefox developer
- Adblock Extension/version: uBlock Origin 1.39.0

### Other details:

Many ad scripts coming from

`https://mp3download.to/js/admir.js`
`https://mp3download.to/js/propellerads_tag.js`
`https://mp3download.to/js/propellerads_tag_onload.js`

Blocking these will defuse the popups

**Comment by JobcenterTycoon** [comment]
They still rotate

`usshcjfsrbvwh.top`
`d1u1byonn4po0b.cloudfront.net/BQmJlTGF9FgwoXHtWVn5Udg%3D%3D`

**Comment by ryanbr** [comment]
Should be resolved.

**Comment by JobcenterTycoon** [comment]
@ryanbr No i still get many requets with popups from unblocked domains like `kbvnqoiolm.top`
